type MarketOverview = {
  exchange: string;
  status: "NORMAL_OPEN" | "NORMAL_CLOSE" | "PRE_OPEN_START" | "PRE_OPEN_END" | "CLOSING_START" | "CLOSING_END";
  observedAt: string;
  dataFresh: boolean;
  regime: "TREND" | "RANGE" | "VOLATILE" | "UNKNOWN";
};

// Read-only UI contract. Values must come from an authenticated backend API in production.
const exampleOverview: MarketOverview = {
  exchange: "NSE",
  status: "NORMAL_CLOSE",
  observedAt: "—",
  dataFresh: false,
  regime: "UNKNOWN",
};

function statusLabel(status: MarketOverview["status"]): string {
  return status.replaceAll("_", " ");
}

export default function MarketOverviewPage() {
  const overview = exampleOverview;

  return (
    <main style={{ margin: "0 auto", maxWidth: 1200, padding: 32 }}>
      <nav style={{ marginBottom: 28 }}>
        <a href="/">← Terminal</a>
      </nav>
      <header style={{ borderBottom: "1px solid #242a31", paddingBottom: 20 }}>
        <p style={{ margin: 0, fontSize: 12, letterSpacing: 1.4, textTransform: "uppercase" }}>Read-only market overview</p>
        <h1 style={{ margin: "8px 0", fontSize: 34 }}>NSE Market State</h1>
        <p style={{ color: "#9ba6b2", margin: 0 }}>No synthetic market values are generated by the frontend.</p>
      </header>

      <section aria-label="Market overview metrics" style={{ display: "grid", gap: 16, gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", marginTop: 28 }}>
        <Metric title="Exchange" value={overview.exchange} />
        <Metric title="Session status" value={statusLabel(overview.status)} />
        <Metric title="Data freshness" value={overview.dataFresh ? "Fresh" : "Unavailable"} />
        <Metric title="Regime" value={overview.regime} />
        <Metric title="Observed at" value={overview.observedAt} />
      </section>

      <aside style={{ border: "1px solid #3a3030", borderRadius: 10, marginTop: 24, padding: 18 }}>
        <strong>Execution boundary</strong>
        <p style={{ color: "#9ba6b2", lineHeight: 1.5, marginBottom: 0 }}>
          This route only renders market-state observations. It cannot submit, amend, cancel, or authorize an order.
          Execution remains a backend RiskEngine → OMS responsibility.
        </p>
      </aside>
    </main>
  );
}

function Metric({ title, value }: { title: string; value: string }) {
  return (
    <article style={{ background: "#11151a", border: "1px solid #242a31", borderRadius: 10, padding: 20 }}>
      <p style={{ color: "#697582", fontSize: 12, margin: "0 0 8px", textTransform: "uppercase" }}>{title}</p>
      <p style={{ fontSize: 21, margin: 0 }}>{value}</p>
    </article>
  );
}
